<?php

	require_once '../config.php';

	if ( ! isset($_GET['job_id']) || empty($_GET['job_id'])){
		flash()->error('missing parameter job id');
		redirect('/company/offered_jobs');
	}
	$user = get_user();
	$job_id = $_GET['job_id'];
	$job = get_company_job($user->id,$job_id);

	if(!$job){
		flash()->error('Something went wrong. Job does not belong to you or is not found.');
		redirect('/company/offered_jobs');
	}

	class PDF extends FPDF
	{
	// Page header
	//	function Header()
	//	{
	//		// Logo
	//		$this->Image('logo.png',10,6,30);
	//		// Arial bold 15
	//		$this->SetFont('Arial','B',15);
	//		// Move to the right
	//		$this->Cell(80);
	//		// Title
	//		$this->Cell(30,10,'Title',1,0,'C');
	//		// Line break
	//		$this->Ln(20);
	//	}

	// Page footer
		function Footer()
		{
			// Position at 1.5 cm from bottom
			$this->SetY(-15);
			// Arial italic 8
			$this->SetFont('Arial','I',8);
			// Page number
			$this->Cell(0,10,'Generated by Jobi app.',0,0,'C');
		}
	}

	// Instanciation of inherited class
	$pdf = new PDF();
	$pdf->AliasNbPages();
	$pdf->AddPage();
	$pdf->SetFont('Times','b',20);
	//for($i=1;$i<=40;$i++)
	//	$pdf->Cell(0,10,'Printing line number '.$i,0,1);
	$pdf->Cell(0,10,$job['title'],0,1);
	$pdf->Cell(0,10,'',0,1);
	$pdf->SetFont('Times','',12);
	$pdf->Cell(0,10,$job['text'],0,1);
	$job_qr_link = '../..'.$job['qr_link'];
	if(file_exists($job_qr_link)) {
		$pdf->Image( $job_qr_link, 10, 60, 50 );
	}
	$pdf->Output('I','job.pdf',true);

